// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxE8y3q4r1yhoICTV6Yl06NygbZ5uXzXs',
    appId: '1:1006287855671:web:99cdc41ae105f44e089fb2',
    messagingSenderId: '1006287855671',
    projectId: 'tpfirebaseauthweb',
    authDomain: 'tpfirebaseauthweb.firebaseapp.com',
    storageBucket: 'tpfirebaseauthweb.firebasestorage.app',
    measurementId: 'G-JYR35YT991',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUNXpm0Ntm08CexSiOdfixptxFVgL6xwA',
    appId: '1:1006287855671:android:d9f9e266d938b590089fb2',
    messagingSenderId: '1006287855671',
    projectId: 'tpfirebaseauthweb',
    storageBucket: 'tpfirebaseauthweb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-gTDPLjoT0sk4It1ByeGTsjvXpJpZXqo',
    appId: '1:1006287855671:ios:214a76bc67f4b2e9089fb2',
    messagingSenderId: '1006287855671',
    projectId: 'tpfirebaseauthweb',
    storageBucket: 'tpfirebaseauthweb.firebasestorage.app',
    iosBundleId: 'com.example.tpFirebaseAuthWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-gTDPLjoT0sk4It1ByeGTsjvXpJpZXqo',
    appId: '1:1006287855671:ios:214a76bc67f4b2e9089fb2',
    messagingSenderId: '1006287855671',
    projectId: 'tpfirebaseauthweb',
    storageBucket: 'tpfirebaseauthweb.firebasestorage.app',
    iosBundleId: 'com.example.tpFirebaseAuthWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxE8y3q4r1yhoICTV6Yl06NygbZ5uXzXs',
    appId: '1:1006287855671:web:9433e534b0032a4c089fb2',
    messagingSenderId: '1006287855671',
    projectId: 'tpfirebaseauthweb',
    authDomain: 'tpfirebaseauthweb.firebaseapp.com',
    storageBucket: 'tpfirebaseauthweb.firebasestorage.app',
    measurementId: 'G-Y5RFB4YPDW',
  );

}